#!/usr/bin/env php
<?php
use Webman\Console\Command;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/support/bootstrap.php';

$cli = new Command();
$cli->setName('webman cli');
$cli->installInternalCommands();
$cli->installCommands(app_path(). '/command');
$cli->run();
